import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Menu from "@/components/Menu/menu"
import Header from "@/components/Header/header"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex w-full">
          <Menu></Menu>
          <div className="h-[100dvh] w-full bg-[#F1F3F6]">
            <Header></Header>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
